In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import oracledb
import getpass
from scipy import stats
from sqlalchemy import create_engine, text

pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

In [3]:
def getODBconn(user, hostname, db, pw = None):
    if pw == None:
        print("Enter password for " + user + "@" + db + ": ")
        pw = getpass.getpass()
    connection=oracledb.connect(user=user, password=pw, host=hostname, service_name=db)
    engine = create_engine('oracle+oracledb://', creator=lambda: connection)
    return engine

In [4]:
eng = getODBconn('VALESA10_SQL', 'AIX47', 'BCDWHPRD')

Enter password for VALESA10_SQL@BCDWHPRD:
········

In [6]:
sql = text('''
SELECT ADDR_NUM, PARENT_ADDR_NUM, NAME_ALPHA, ADDRESS_LINE_1, ADDRESS_LINE_2, ADDRESS_LINE_3, ADDRESS_LINE_4, CITY, STATE_CD, STATE, ZIP, COUNTY, COUNTRY_CD, COUNTRY, LATITUDE, LONGITUDE
    FROM CUSTOMER 
    WHERE country_cd = 'US'
    AND STANDARD_INDUSTRY_CD = 'FH'
''')

In [7]:
cnx = eng.connect()
qry = cnx.execute(sql)
sql_df = pd.DataFrame(qry.fetchall())
sql_df.columns = qry.keys()

In [9]:
sql_df[sql_df['latitude'] != 0]

,addr_num,parent_addr_num,name_alpha,address_line_1,address_line_2,address_line_3,address_line_4,city,state_cd,state,zip,county,country_cd,country,latitude,longitude
2,143749,143749,04572 SKILLIN-CARROLL MORTUARY,738 EAST SANTA PAULA STREET,,,,SANTA PAULA,CA,California,93060-2069,VENTURA,US,USA,34.3557896,-119.0664124
3,333426,333426,6878 PRINEVILLE FUNERAL HOME,199 EAST 10TH ST,,,,PRINEVILLE,OR,Oregon,97754-1201,CROOK,US,USA,44.30898,-120.84619
4,141261,141261,4244 PERLMAN FUNERAL HOME INC.,1026 MAIN ST,,,,WORCESTER,MA,Massachusetts,01603-2424,WORCESTER,US,USA,42.2467900003,-71.8285350003
6,145844,145844,7275 CAROTHERS FUNERAL HOME,312 W. 2ND. AVENUE,,,,GASTONIA,NC,North Carolina,28052-4002,GASTON,US,USA,35.26062,-81.186355
7,142888,142888,04732 GRIGGS-SCHOOLER-GORDON FUNERAL DIR,5400 BELL AVENUE,,,,AMARILLO,TX,Texas,79109-6222,POTTER,US,USA,35.1539218023,-101.9000364525
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42823,307159,136021,KEITH D. BIGLOW FUNERAL DIRECTORS,1414 N NORFOLK AVE,,,,TULSA,OK,Oklahoma,74106-4405,TULSA,US,USA,36.1754332,-95.9778584
42824,346354,132436,GILL FUNERAL HOME INC.-870,308 E WALNUT ST,,,,WASHINGTON,IN,Indiana,47501-2761,DAVIESS,US,USA,38.658633,-87.172194
42825,152056,152056,MARRON FUNERAL HOME,808 SOMERSET AVE.,,,,WINDBER,PA,Pennsylvania,15963-1431,SOMERSET,US,USA,40.2406913919,-78.83603258
42826,350010,350010,"PACIOREK FUNERAL HOME, INC",13 HOOSAC,,,,ADAMS,MA,Massachusetts,01220-1733,BERKSHIRE,US,USA,42.625025,-73.115265
42827,378027,378027,O'SHAUGHNESSY CO. FUNERAL DIRECTORS LLC,229 E STATE ST.,,,,COLUMBUS,OH,Ohio,43215,FRANKLIN,US,USA,39.9608932,-82.9939944