In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import oracledb
import getpass
from scipy import stats
from sqlalchemy import create_engine, text

pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

In [12]:
scm = pd.read_excel('../../../../data/2024-09-01 Standard Coverage Model.xlsx', sheet_name= 'CVG Model');

In [2]:
def getODBconn(user, hostname, db, pw = None):
    if pw == None:
        print("Enter password for " + user + "@" + db + ": ")
        pw = getpass.getpass()
    connection=oracledb.connect(user=user, password=pw, host=hostname, service_name=db)
    engine = create_engine('oracle+oracledb://', creator=lambda: connection)
    return engine

In [3]:
eng = getODBconn('VALESA10_SQL', 'AIX47', 'BCDWHPRD')

Enter password for VALESA10_SQL@BCDWHPRD:
········

In [4]:
sql = text('''
SELECT ADDR_NUM, PARENT_ADDR_NUM, NAME_ALPHA, ADDRESS_LINE_1, ADDRESS_LINE_2, ADDRESS_LINE_3, ADDRESS_LINE_4, CITY, STATE_CD, STATE, ZIP, COUNTY, COUNTRY_CD, COUNTRY, LATITUDE, LONGITUDE
    FROM CUSTOMER 
    WHERE country_cd = 'US'
    AND STANDARD_INDUSTRY_CD = 'FH'
''')

In [5]:
cnx = eng.connect()
qry = cnx.execute(sql)
sql_df = pd.DataFrame(qry.fetchall())
sql_df.columns = qry.keys()

In [38]:
sql_df

,addr_num,parent_addr_num,name_alpha,address_line_1,address_line_2,address_line_3,address_line_4,city,state_cd,state,zip,county,country_cd,country,latitude,longitude
0,131827,131827,2536 FAMILY FUNERAL CARE,13001 KATY FWY,,,,HOUSTON,TX,Texas,77079-1407,,US,USA,0,0
1,150083,150361,4235 FAMILY FUNERAL CARE,1201 N. ARENDELL AVE.,,,,ZEBULON,NC,North Carolina,27597-8731,WAKE,US,USA,0,0
2,143749,143749,04572 SKILLIN-CARROLL MORTUARY,738 EAST SANTA PAULA STREET,,,,SANTA PAULA,CA,California,93060-2069,VENTURA,US,USA,34.3557896,-119.0664124
3,333426,333426,6878 PRINEVILLE FUNERAL HOME,199 EAST 10TH ST,,,,PRINEVILLE,OR,Oregon,97754-1201,CROOK,US,USA,44.30898,-120.84619
4,141261,141261,4244 PERLMAN FUNERAL HOME INC.,1026 MAIN ST,,,,WORCESTER,MA,Massachusetts,01603-2424,WORCESTER,US,USA,42.2467900003,-71.8285350003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42834,173918,173918,BROWN-MCCLAY FUNERAL HOME,PO BOX 197,,,,BRISTOL,VT,Vermont,05443-0197,,US,USA,0,0
42835,287086,287086,"SIMONS-COLEMAN FUNERAL HOME,INC.",PO BOX 647,,,,RICHWOOD,WV,West Virginia,26261-0647,,US,USA,0,0
42836,723127,151849,CROSBY & NEAL FUNERAL HOME,PO BOX 371,,,,DEXTER,ME,Maine,04930-0371,,US,USA,0,0
42837,314504,314504,G LANE FUNERAL HOME,P.O. BOX 30035,,,,GREENVILLE,NC,North Carolina,27833-0035,PITT,US,USA,0,0
42838,301278,301278,STEBBINS MC CULLOUGH FUNERAL HOME,PO BOX 21,,,,EDMORE,MI,Michigan,48829,,US,USA,0,0

In [39]:
scm

,Ship To #,Ship To Name,Parent #,Parent Name,City,State,Country,Division,Region Code,Region Desc,Territory Cd,Rep Name,Status \n(C-Open;\n CO-Closed),Customer Group Code,Customer Group,Customer Segment,Program Sub-Group 2,Program Sub-Group 1,Customer Spectrum,Representative Type,NAR Code,NAR Manager,Std Industry Cd,Customer Type,Tot Dths,Burials,Adj. Burials,Program,Cost Center / CSC,CSC Desc,Serv Lvl,Delivery Frequency,Delivery Service Priority,Buyer Type,Burial Units Prior Mo,Net Burial $$$ Prior Mo,Metal Units Prior Mo,Wood Units Prior Mo,Feature Units Prior Mo,Net Feature $$$ Prior Mo,Constellation Units Prior Mo,Net Constellation $$$ Prior Mo,Net Cremation $$$ Prior Mo,Net BI $$$ Prior Mo,Net Total $$$ Prior Mo,Burial Units Prior Mo PY,Net Burial $$$ Prior Mo PY,Metal Units Prior Mo PY,Wood Units Prior Mo PY,Feature Units Prior Mo PY,Net Feature $$$ Prior Mo PY,Constellation Units Prior Mo PY,Net Constellation $$$ Prior Mo PY,Net Cremation $$$ Prior Mo PY,Net BI $$$ Prior Mo PY,Net Total $$$ Prior Mo PY,Burial Units YTD,Net Burial $$$ YTD,Metal Units YTD,Wood Units YTD,Feature Units YTD,Net Feature $$$ YTD,Constellation Units YTD,Net Constellation $$$ YTD,Net Cremation $$$ YTD,Net BI $$$ YTD,Net Total $$$ YTD,Burial Units PYTD,Net Burial $$$ PYTD,Metal Units PYTD,Wood Units PYTD,Feature Units PYTD,Net Feature $$$ PYTD,Constellation Units PYTD,Net Constellation $$$ PYTD,Net Cremation $$$ PYTD,Net BI $$$ PYTD,Net Total $$$ PYTD,Burial Units Rolling 12 mo,Net Burial $$$ Rolling 12 mo,Metal Units Rolling 12 mo,Wood Units Rolling 12 mo,Feature Units Rolling 12 mo,Net Feature $$$ Rolling 12 mo,Constellation Units Rolling 12 mo,Net Constellation $$$ Rolling 12 mo,Net Cremation $$$ Rolling 12 mo,Net BI $$$ Rolling 12 mo,Net Total $$$ Rolling 12 mo,Burial Units Rolling 12 mo PY,Net Burial $$$ Rolling 12 mo PY,Metal Units Rolling 12 mo PY,Wood Units Rolling 12 mo PY,Feature Units Rolling 12 mo PY,Net Feature $$$ Rolling 12 mo PY,Constellation Units Rolling 12 mo PY,Net Constellation $$$ Rolling 12 mo PY,Net Cremation $$$ Rolling 12 mo PY,Net BI $$$ Rolling 12 mo PY,Net Total $$$ Rolling 12 mo PY,Burial Units PY,Net Burial $$$ PY,Metal Units PY,Wood Units PY,Feature Units PY,Net Feature $$$ PY,Constellation Units PY,Net Constellation $$$ PY,Net Cremation $$$ PY,Net BI $$$ PY,Net Total $$$ PY,Burial Units 2PY,Net Burial $$$ 2PY,Metal Units 2PY,Wood Units 2PY,Feature Units 2PY,Net Feature $$$ 2PY,Constellation Units 2PY,Net Constellation $$$ 2PY,Net Cremation $$$ 2PY,Net BI $$$ 2PY,Net Total $$$ 2PY,Line 1,Line 2,Line 3,Zip Code
0,128225,"TRIBORO FUNERAL HOME, INC",128225,"TRIBORO FUNERAL HOME, INC",NEW YORK,NY,US,A DIVISION,B1,ALLENTOWN NE,03,"CHUDNOVSKY, HAROLD",C,,NaN,AEP,,,Independent,Acct Exec,,NaN,FH,FP,50.0,20,20,PAA,8023,CSC MOONACHIE INVENTORY,MM TT WW RR FF SS,12 x per week,4,Buyer,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,1.0,669.00,1.0,0.0,0.0,0.00,1.0,669.00,0.0,0.0,669.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.00,1.0,669.00,1.0,0.0,0.0,0.00,1.0,669.00,0.0,0.0,669.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.0,0.00,2274 ADAM CLAYTON POWEL JR BLVD,,,10030
1,141419,"JOHN B. HOUSTON FUNERAL HOME, INC",128225,"TRIBORO FUNERAL HOME, INC",PATERSON,NJ,US,A DIVISION,B1,ALLENTOWN NE,03,"CHUDNOVSKY, HAROLD",C,,NaN,AEP,,,Independent,Acct Exec,,NaN,FH,FP,55.0,22,68,PAA,8023,CSC MOONACHIE INVENTORY,MM TT WW RR FF SS,12 x per week,4,Buyer,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,10.0,7127.70,10.0,0.0,1.0,749.0,8.0,5050.70,0.00,0.0,7127.7,62.0,51023.60,60.0,2.0,6.0,8379.52,54.0,39967.60,0.0,0.0,51023.60,59.0,38331.2,59.0,0.0,1.0,749.00,57.0,36254.2,0.00,0.0,38331.20,68.0,54815.50,66.0,2.0,6.0,8379.52,60.0,43759.50,0.0,0.0,54815.50,62.0,39784.20,62.0,0.0,1.0,749.00,60.0,37707.2,0.00,0.0,39784.2,65.0,42123.10,65.0,0.0,1.0,749.00,63.0,40046.1,0.00,0.0,42123.10,7.0,3689.00,7.0,0.0,0.0,0.00,7.0,3689.00,0.00,0.0,3689.00,DBA CUSHNIE-HOUSTON FUNERAL HOME,236 ELLISON ST,,7501
2,883852,CUSHNIE-HOUSTON FUNERAL HOME,128225,"TRIBORO FUNERAL HOME, INC",EAST ORANGE,NJ,US,A DIVISION,B1,ALLENTOWN NE,03,"CHUDNOVSKY, HAROLD",C,,NaN,AEP,,,Independent,Acct Exec,,NaN,FH,FP,30.0,12,16,PAA,8023,CSC MOONACHIE INVENTORY,,NaN,4,Buyer,1.0,2799.36,1.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,2799.36,2.0,1137.30,2.0,0.0,0.0,0.0,2.0,1137.30,0.00,0.0,1137.3,13.0,17608.35,11.0,2.0,2.0,2501.12,8.0,6107.55,0.0,0.0,17608.35,10.0,14786.7,9.0,1.0,0.0,0.00,7.0,4880.7,196.35,0.0,14983.05,16.0,21699.35,14.0,2.0,2.0,2501.12,10.0,7654.55,0.0,0.0,21699.35,11.0,19365.45,9.0,2.0,0.0,0.00,7.0,4880.7,514.25,0.0,19879.7,13.0,18877.70,12.0,1.0,0.0,0.00,9.0,6427.7,196.35,0.0,19074.05,6.0,17591.50,5.0,1.0,0.0,0.00,1.0,559.00,317.90,0.0,17909.40,102 SANFORD ST,,,07018-1903
3,128834,HARTMANN FUNERAL HOME,128834,HARTMANN FUNERAL HOME,MERCERVILLE,NJ,US,A DIVISION,B1,ALLENTOWN NE,03,"CHUDNOVSKY, HAROLD",C,,NaN,AEP,,URN,Independent,Acct Exec,,NaN,FH,FP,84.0,42,42,SPP,8048,RDC ALLENTOWN INVENTORY,M T W R F S,6 x per week,5,Buyer,1.0,1325.35,1.0,0.0,1.0,1325.35,0.0,0.0,0.0,0.0,1325.35,1.0,543.15,1.0,0.0,0.0,0.0,1.0,543.15,332.35,0.0,875.5,28.0,38542.65,27.0,1.0,12.0,16714.75,2.0,1324.30,3882.8,0.0,42425.45,23.0,34198.2,17.0,6.0,9.0,13585.65,3.0,1769.7,5292.95,0.0,39491.15,31.0,42926.90,30.0,1.0,12.0,16714.75,2.0,1324.30,3882.8,0.0,46809.70,26.0,40194.45,20.0,6.0,9.0,13585.65,3.0,1769.7,6142.95,0.0,46337.4,26.0,38582.45,20.0,6.0,9.0,13585.65,3.0,1769.7,5292.95,0.0,43875.40,33.0,43598.59,31.0,2.0,9.0,10500.75,2.0,1267.34,5421.78,0.0,49020.37,2830 NOTTINGHAM WAY,,,08619-1857
4,128976,JOHNSON JR INC,128976,JOHNSON JR INC,NORRISTOWN,PA,US,A DIVISION,B1,ALLENTOWN NE,03,"CHUDNOVSKY, HAROLD",C,,NaN,AEP,SS,TAB,Independent,Acct Exec,,NaN,FH,FP,35.0,25,25,GRO,8048,RDC ALLENTOWN INVENTORY,M T W R F S,6 x per week,5,Casual Buyer,1.0,599.00,1.0,0.0,0.0,0.00,1.0,599.0,0.0,0.0,599.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,1.0,599.00,1.0,0.0,0.0,0.00,1.0,599.00,0.0,0.0,599.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.00,1.0,599.00,1.0,0.0,0.0,0.00,1.0,599.00,0.0,0.0,599.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.00,1.0,1190.00,1.0,0.0,0.0,0.00,0.0,0.00,0.00,0.0,1190.00,800 WEST MAIN ST,,,19401-5502
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41908,165176,PERCHES FUNERALES,165176,PERCHES FUNERALES,EL PASO,TX,US,INT'L DIVISION,D5,MEXICO,W1,MEXICO,CO,,NaN,IL,,,International,International,,NaN,FH,FP,0.0,0,20,,8333,"CSC EL PASO, TX",M T W R F,5 x per week,5,Non-Buyer,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,1.0,2505.00,1.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,2505.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.00,1.0,2505.0,1.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,2505.00,-1.0,-2505.00,-1.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,-2505.00,1.0,2505.00,1.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,2505.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.0,0.00,3331 ALAMEDA AVE,,,79905
41909,196523,SOUTH AUSTRALIA,196523,SOUTH AUSTRALIA,ADELAIDE AIPORT,,AU,INT'L DIVISION,D5,MEXICO,W1,MEXICO,CO,,NaN,IL,,,International,International,,NaN,OF,FP,0.0,0,20,,8061,CSC - INTERNATIONAL,,NaN,0,Non-Buyer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BAX GLOBAL,"UNIT 3, BUILDING A, EXPORT PARK",,5950
41910,196524,BAX GLOBAL KEWDALE,196524,BAX GLOBAL KEWDALE,KEWDALE,,AU,INT'L DIVISION,D5,MEXICO,W1,MEXICO,CO,,NaN,IL,,,International,International,,NaN,OF,FP,0.0,0,20,,8061,CSC - INTERNATIONAL,,NaN,0,Non-Buyer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,523 ABERNATHY ROAD,,,
41911,196527,BETA CASKETS AUSTRALIA,196527,BETA CASKETS AUSTRALIA,"FAIRFIELD, NSW",,AU,INT'L DIVISION,D5,MEXICO,W1,MEXICO,CO,,NaN,IL,,,International,International,,NaN,OF,FP,0.0,0,20,,8061,CSC - INTERNATIONAL,,NaN,0,Non-Buyer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100 FAIRFIELD ST,,,2165
41912,196528,DUEREMER SARGFABRIK GERMAN,196528,DUEREMER SARGFABRIK GERMAN,,,,INT'L DIVISION,D5,MEXICO,W1,MEXICO,CO,,NaN,IL,,,International,International,,NaN,OF,,0.0,0,0,,8061,CSC - INTERNATIONAL,,NaN,0,Non-Buyer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,,

In [40]:
scm['Ship To #'] = scm['Ship To #'].astype(str)

In [41]:
sql_df['addr_num'] = sql_df['addr_num'].astype(str)

In [42]:
joined_df = pd.merge(sql_df, scm, how='left', right_on='Ship To #', left_on='addr_num')

In [45]:
joined_df[joined_df['latitude'] != 0].to_csv('../../data/test_points.csv')